[[redirects]]
  from = "serene-villani-dc4cb5.netlify.app"
  to = "echo-breaking-news.com"
  status = 301
  force = true

  [[headers]]
  for = "staging.echo-breaking-news.com/*"
  [headers.values]
    X-robots-tag = "noindex"