[[redirects]]
  from = "serene-villani-dc4cb5.netlify.app"
  to = "echo-breaking-news.com"
  status = 301
  force = true

  [[headers]]
  for = "/*"
  [headers.values]
    Link = '<https://echo-breaking-news.com/>; rel="canonical"'
    X-robots-tag = "noindex"